import "./privacy-policy.css";

const privacyMeta = [
  ["Effective Date", "July 9, 2026"],
  ["Last Updated", "July 9, 2026"],
  ["Owner / Operator", "Kazi Faizullah"],
  ["Website", "EnglishCommando.bd"],
  ["Privacy Contact", "privacy@englishcommando.bd"],
];

const privacySections = [
  ["1. Introduction", "This Privacy Policy explains how English Commando collects, uses, stores, protects, shares, and deletes personal information when users access or use our website, web application, Android application, online classes, recorded videos, AI-based learning tools, communication systems, payment services, and related features. English Commando is a comprehensive online English communication training platform built to improve users' English communication, speaking, listening, reading, writing, vocabulary development, pronunciation, discipline, confidence, and learning consistency."],
  ["2. Who We Are", "English Commando is owned and operated by Kazi Faizullah. \"English Commando,\" \"we,\" \"our,\" or \"us\" refers to English Commando and its owner/operator. Website: EnglishCommando.bd. Privacy Contact: privacy@englishcommando.bd."],
  ["3. Acceptance of This Privacy Policy", "By creating an account, enrolling in a course, using English Commando, joining a live class, watching recorded lessons, submitting learning tasks, allowing app permissions, making a payment, requesting a refund, contacting support, or continuing to use our services, you confirm that you have read and understood this Privacy Policy. Users under 18 should use the service with permission from a parent, legal guardian, school, or responsible adult."],
  ["4. Information We Collect", "We may collect account and profile data such as name, phone number, email address, password, profile photo, age, class, school, location, student details, and guardian details. Learning data may include course progress, quiz marks, vocabulary practice, speaking and pronunciation activity, writing practice, assignments, attendance, reminders, performance scores, AI feedback, and learning behavior patterns. We may also process voice recordings, audio or video submissions, live class participation, uploaded materials, IP address, device information, app usage, payment status, transaction information, and communication history."],
  ["5. How We Use Information", "We use information to create and manage accounts, provide learning services, operate classes and recorded lessons, personalize study plans, evaluate tasks, track progress, send reminders, provide human and AI-supported feedback, process payments and refunds, provide support, secure the platform, prevent fraud or misuse, improve features, and comply with legal obligations. We may contact learners or guardians by phone, AI call, SMS, WhatsApp, email, push notification, or in-app message for service communication."],
  ["6. Learning Support", "Live classes, recorded videos, structured tasks, discipline-based routines, reminders, daily follow-up, and personal learning support may require processing attendance, activity, submitted tasks, class participation, learning performance, media activity, and communication records."],
  ["7. AI-Based Learning Features and AI Calls", "AI-powered tools may support learning, analysis, feedback, reminders, practice, pronunciation, writing, speaking evaluation, task review, personalized suggestions, and communication. AI features may process written and spoken responses, voice recordings, quiz results, learning history, mistakes, performance records, and communication data. AI-generated results are for educational support and may not always be perfect."],
  ["8. Mobile App Permissions", "Depending on the feature used, the app may request camera, microphone, storage or files, notifications, internet/network, and location access for profile photos, video learning, live class, speaking practice, uploads, security, attendance, reminders, payment notices, refund updates, and platform notices. Some features may not work if permissions are disabled."],
  ["9. Shareable Learner Profiles", "A learner or guardian may choose to share a profile link. A shareable profile may include selected information such as name, photo, learning level, progress, achievements, badges, scores, certificates, or public learning status. Passwords, private payment data, internal notes, and private communication records should not be displayed publicly."],
  ["10. Payments, Subscriptions, and Refunds", "Payments may be processed through providers such as bKash, Nagad, Rocket, card payment providers, SSLCommerz, or other authorized services. We may use transaction information to activate courses, verify payments, manage subscriptions, issue invoices, provide support, investigate issues, prevent fraud, and process refunds. We do not intentionally store full card numbers, banking passwords, card PINs, or mobile banking PINs."],
  ["11. Cookies and Tracking Technologies", "We may use cookies, local storage, pixels, SDKs, analytics tools, and similar technologies to keep users logged in, remember preferences, analyze usage, improve performance, measure marketing, prevent fraud, fix errors, and improve learning features. Third-party services such as Google Analytics, Firebase, Meta Pixel, YouTube, Google Meet, WhatsApp, AI tools, SMS, email, payment, and hosting providers may process information under their own policies."],
  ["12. Sharing of Information", "We do not sell personal information. We may share information with trusted hosting, payment, analytics, messaging, AI, video/class, email, SMS, technical support, and security providers. Authorized teachers, mentors, support staff, or admins may access limited learner information when necessary for assigned duties. We may disclose information if required by law or necessary to protect users, prevent fraud, investigate security issues, enforce terms, protect rights, or respond to emergencies."],
  ["13. Data Storage and International Processing", "Data may be stored on Hostinger VPS and other hosting, cloud, database, backup, or technical infrastructure. Depending on hosting location and third-party services, information may be stored or processed in Bangladesh or outside Bangladesh."],
  ["14. Data Security", "We use reasonable technical and organizational measures including HTTPS/SSL, password hashing or encryption, role-based access controls, limited admin access, server controls, backups, monitoring, logging, and secure third-party payment processing. No online platform or internet transmission is 100% secure. Users should protect passwords and OTPs and avoid sharing login information."],
  ["15. Data Retention", "We keep information as long as necessary to provide services, maintain learning history, manage accounts, provide support, process payments and refunds, prevent fraud, resolve disputes, comply with legal obligations, enforce agreements, and maintain security. Backup, security, payment, fraud-prevention, dispute, or legally required records may remain for up to 90 days or longer if required by law."],
  ["16. Account Deletion and User Requests", "Users may request account or data deletion through an in-app option, website deletion form or page, or by contacting privacy@englishcommando.bd. Users may also request access, correction, profile updates, deletion, withdrawal of consent where applicable, or answers to privacy questions."],
  ["17. Children and Students Under 18", "Use by children, teenagers, and students under 18 should happen with permission from a parent, legal guardian, school, or responsible adult. Parents or guardians may contact us to review, correct, or request deletion of a child's personal information and should supervise use of classes, AI features, profiles, communication tools, and app permissions."],
  ["18. Marketing and Service Communication", "We may send class reminders, task reminders, course updates, payment notices, refund updates, security alerts, promotional offers, and important announcements through SMS, phone, AI call, WhatsApp, email, push notification, or in-app message. Users may opt out of promotional communication, but important account, payment, security, legal, or service messages may still be sent."],
  ["19. Intellectual Property Notice", "English Commando content, systems, methods, learning structures, designs, source code, software, videos, audio, graphics, vocabulary systems, class materials, AI workflows, features, names, branding, and related materials are owned by or licensed to English Commando and Kazi Faizullah. Copying, distributing, selling, publishing, scraping, cloning, reverse engineering, or commercial exploitation without written permission is prohibited."],
  ["20. Third-Party Websites and Services", "Links, embedded content, payment flows, videos, class tools, messaging tools, or integrations provided by third parties are governed by their own privacy policies and terms. We are not responsible for practices of third-party services we do not control."],
  ["21. Changes to This Privacy Policy", "We may update this Privacy Policy from time to time. Major changes may be notified through the app, website, email, SMS, WhatsApp, push notification, or another reasonable method. Continued use after changes means users accept the updated policy."],
  ["22. Contact Us", "For privacy questions, account deletion requests, data correction requests, complaints, or other privacy matters, contact English Commando at privacy@englishcommando.bd."],
  ["23. Consent", "By using English Commando, creating an account, submitting information, allowing permissions, joining classes, watching videos, using AI features, making payments, requesting refunds, or participating in learning activities, users confirm that they have read and understood this Privacy Policy and agree to the collection, use, storage, processing, sharing, retention, and deletion of information described here. For users under 18, the responsible parent, guardian, school, or adult confirms permission."],
];

export default function PrivacyPolicy() {
  return (
    <section className="privacy-page" id="privacy-policy">
      <div className="privacy-header"><div className="privacy-shell">
        <a className="privacy-back" href="/">← হোমে ফিরে যান</a>
        <div className="privacy-intro"><p className="privacy-eyebrow">English Commando</p><h1>Privacy Policy</h1><p className="privacy-summary">এই নীতিমালা English Commando কীভাবে ব্যক্তিগত তথ্য সংগ্রহ, ব্যবহার, সংরক্ষণ, সুরক্ষা, শেয়ার এবং মুছে ফেলে তা ব্যাখ্যা করে।</p></div>
      </div></div>
      <div className="privacy-content"><div className="privacy-meta-grid">{privacyMeta.map(([label, value]) => <div className="privacy-meta-card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{privacySections.map(([title, paragraph]) => <article className="privacy-section" key={title}><h2>{title}</h2><p>{paragraph}</p></article>)}</div>
    </section>
  );
}
